name: Deploy to S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Fetch GitHub Actions IP ranges
        run: |
          wget https://api.github.com/meta
          cat meta | jq -r '.actions[].cidr_blocks[]' > github_actions_ip_ranges.txt

      - name: Update IAM policy with GitHub Actions IP ranges
        run: |
          powershell -ExecutionPolicy Bypass -File Update-IAMPolicy.ps1

      - name: Install project dependencies
        run: npm install

      - name: Build Gatsby project
        run: gatsby build

      - name: Upload to S3 bucket
        run: |
          aws s3 sync public/ s3://hoff-portfolio